{{- if and (index .Values "cert-manager") (index .Values "cert-manager" "enable") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: cert-manager
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: charts/addons/cert-manager
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: cert-manager
  destination:
    name: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ (index .Values "cert-manager" "createNamespace") }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
